# Development, runs mongodb,  fastapi app from api folder and vuejs web-app app from frontend folder
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8066"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://localhost:27017/

#  vuejs:
#    image: node:20
#    volumes:
#      - ./frontend:/app
#    working_dir: /app
#    command: bash -c "npm install && npm run serve"
#    ports:
#      - "8080:8085"
#  fastapi:
#    build:
#      context: .
#      dockerfile: api/Dockerfile
#    command: uvicorn main:app --host 0.0.0.0 --reload
#    volumes:
#      - ./api:/app
#    ports:
#      - "8000:8084"
#    depends_on:
#      - mongodb
      
volumes:
  mongodbdata:
