# Development: MongoDB, FastAPI backend, Angular frontend, Mongo Express admin
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8083:8081"
  frontend:
    image: node:22
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npx ng serve --host 0.0.0.0 --port 8085 --configuration=local"
    ports:
      - "8085:8085"
    depends_on:
      - fastapi
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8084:8000"
    environment:
      - ocadb.MONGODB_URL=mongodb://mongodb:27017
      - ocadb.MONGODB_DATABASE=ocadb
    depends_on:
      - mongodb

volumes:
  mongodbdata:
