# Development, runs mongodb,  fastapi app from api folder and vuejs web-app app from frontend folder
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8083:8081"
  vuejs:
    image: node:20
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm run serve"
    ports:
      - "8085:8080"
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./api:/app
    ports:
      - "8084:8000"
    depends_on:
      - mongodb
      
volumes:
  mongodbdata:
